### ISSUE TITLE
Base image reference need to be updated

### ISSUE THREAD

**Issue by sabre1041** [johwes/bootc-quarkus-optaplanner#1]
The location of the base images have changed. Update the `Containerfiles` to reference the following locations:

* quay.io/centos-boot/fedora-boot-cloud:eln -> quay.io/centos-bootc/fedora-bootc-cloud:eln
* quay.io/centos-boot/fedora-tier-1:eln -> quay.io/centos-bootc/fedora-bootc:eln

**Comment by johwes** [comment]
Done. Thanks for opening the issue!
